In [1]:
import numpy as np

In [2]:
from dust_gan import DustDCGAN,DCGAN

d:\my_pythonanaconda3\envs\dust_gan_env\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [3]:
t1 = DCGAN(load_state=True)

Loading Previous State


d:\my_pythonanaconda3\envs\dust_gan_env\lib\site-packages\keras\models.py:282: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '


In [6]:
t1.discriminator()
t1.adversarial_model()
t1.discriminator_model()

In [7]:
t1.generator()

In [8]:
t1.G.get_layer('conv2d_transpose_1').get_weights()[0][:,:,0,0]

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [14]:
t1.G.get_layer('conv2d_transpose_1').set_weights([1*np.ones([5,5,128,256]),np.ones(128)])

In [15]:
t1.G.get_layer('conv2d_transpose_1').get_weights()[0][:,:,0,0]

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [11]:
t1.save_dcgan()

In [16]:
t1.load_dcgan()

d:\my_pythonanaconda3\envs\dust_gan_env\lib\site-packages\keras\models.py:282: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '


In [17]:
t1.G.get_layer('conv2d_transpose_1').get_weights()[0][:,:,0,0]

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]], dtype=float32)

In [5]:
from keras.models import Sequential, model_from_json, load_model


In [8]:
g=load_model('G_model.h5')

d:\my_pythonanaconda3\envs\dust_gan_env\lib\site-packages\keras\models.py:282: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '


In [10]:
g.get_layer('conv2d_transpose_1').get_weights()[0][:,:,0,0]

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)